version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile  
    command: ["python", "bot.py"]  
    restart: on-failure:3
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 
    restart: always
    ports:
      - "8000:8000"
